"""work_log_title

Revision ID: 2da31d70a0ae
Revises: fbffe86e9e4b
Create Date: 2026-07-15 16:41:29.927378
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '2da31d70a0ae'
down_revision: str | None = 'fbffe86e9e4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_work_logs', sa.Column('title', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_work_logs', 'title')
    # ### end Alembic commands ###
