"""task_timer_and_work_logs

Revision ID: fbffe86e9e4b
Revises: 634996a59af6
Create Date: 2026-07-15 14:54:16.020806
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'fbffe86e9e4b'
down_revision: str | None = '634996a59af6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
